### PR TITLE
Initial support for S3 direct uploads

### PR DESCRIPTION
**Pull request by intsco**
- fine-uploader for uploading to S3
- upload.js - initialization of fine-uploader and file upload validation
- webpack.config.js, package.json - new js libs and webpack loaders
- index.html - html template for fine uploader UI
- app.py - UploadHandler class for signing fine uploader's requests to S3
- index.jsx - not very successful attempt of using functions from upload.js

---

This change is [Reviewable](https://reviewable.io/reviews/alexandrovteam/maori-upload/2)

### CODE REVIEW

**Comment by intsco** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[a discussion](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIF7KwsjAh9gB0oZxPe:-KIF7KwtsbSrVvslxDlz:-433629867) (no related file):_
@lomereiter Your help is needed for integrating upload.js into index.jsx. At the moment it just doesn't work.
@DarthPumpkin app.py review

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by lomereiter** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[static/index.jsx, line 7 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMCekIU_fy2_CjfU4H:-KIMCekIU_fy2_CjfU4I:-1470845946) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/index.jsx#L7)):_

> ``` JSX
> import $ from 'jquery'
> import customValidation from './validation'
> import init_uploader from './upload'
> ```

please use lower camel case in JS code

---

_[static/upload.js, line 20 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMDw1PXsKf9xtL2Yl3:-KIMDw1Q0SzCwjgHDP-X:987472844) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L20)):_

> ``` JavaScript
>                 var folder = Cookies.get("session_id");
>                 return folder + '/' + s3Uploader.getFile(id).name;
>             }
> ```

you could use ES6 syntax here: 

``` javascript
key: (id) => `${Cookies.get("session_id")}/${s3Uploader.getFile(id).name}`
```

---

_[static/upload.js, line 63 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMFYLwwR233x89mYlm:-KIMFYLwwR233x89mYln:694674687) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L63)):_

> ``` JavaScript
>         for (var i in uploads) {
>             fnames.push(uploads[i].name);
>         }
> ```

in ES6 you can simply use `getUploads().map((x) => x.name)`

---

_[static/upload.js, line 70 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMHNoyh5fiUgqFMINs:-KIMHNozOWpg4Ri8GRQe:-188897925) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L70)):_

> ``` JavaScript
>         }
> 
>         if (fnames[0].split('.')[0] != fnames[1].split('.')[0]) {
> ```

1) we should compare `split('.').slice(0, -1)` to handle cases like A.centroided.imzML + A.raw.ibd
2) extensions should also be checked

---

_[static/upload.js, line 80 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMIc6xeTXa-RdrFl28:-KIMIc6yKJrbmDSeC0Ds:-243992269) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L80)):_

> ``` JavaScript
> 
> function add_upload_trigger(s3Uploader) {
>     $('#trigger-upload').click(function() {
> ```

http://stackoverflow.com/questions/37018258/how-to-use-fine-uploader-in-react-js

In the end, this file should export a React component that can be used instead of index.jsx/DirectUploadForm

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by lomereiter** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[static/upload.js, line 80 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMIc6xeTXa-RdrFl28:-KIMLr--oyTxxZKZMvhi:1186386220) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L80)):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> http://stackoverflow.com/questions/37018258/how-to-use-fine-uploader-in-react-js
> 
> In the end, this file should export a React component that can be used instead of index.jsx/DirectUploadForm
> </details>
> Also, validation should be done using `onValidateBatch` callback: http://docs.fineuploader.com/api/events.html#validateBatch

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by intsco** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[static/upload.js, line 70 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMHNoyh5fiUgqFMINs:-KIMaAe0cujiXLy2ME6x:594657748) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L70)):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> 1) we should compare `split('.').slice(0, -1)` to handle cases like A.centroided.imzML + A.raw.ibd
> 2) extensions should also be checked
> </details>
> 1) totaly agree
> 2) extension checking is provided by fine uploader

---

_[static/upload.js, line 80 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMIc6xeTXa-RdrFl28:-KIPOZXEgAmgtiKK0PtW:-782216994) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L80)):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> Also, validation should be done using `onValidateBatch` callback: http://docs.fineuploader.com/api/events.html#validateBatch
> </details>
> Suprisingly onValidateBatch is called every time a new file is choosen. Not very usefull when one wants to validate several files at once.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by rnicholus** [comment]
> Suprisingly onValidateBatch is called every time a new file is choosen. Not very usefull when one wants to validate several files at once.

`onValidateBatch` is only called for each batch of files. If only single file is selected via a file input or dropped onto a drop zone, this is indeed a batch. If you are seeing different behavior or have some suggestions regarding an alternate way to group files, please [open an issue](https://github.com/FineUploader/fine-uploader/issues) to start a discussion.

**Comment by intsco** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[static/index.jsx, line 7 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMCekIU_fy2_CjfU4H:-KIRmzSQkmI6LDqB3VAj:-499146009) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/index.jsx#L7)):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> please use lower camel case in JS code
> </details>
> Done.

---

_[static/upload.js, line 20 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMDw1PXsKf9xtL2Yl3:-KISHl1ZuH-GJ4dJDbqH:-499146009) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L20)):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> you could use ES6 syntax here: 
> 
> ``` javascript
> key: (id) => `${Cookies.get("session_id")}/${s3Uploader.getFile(id).name}`
> ```
> 
> </details>
> Done.

---

_[static/upload.js, line 63 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMFYLwwR233x89mYlm:-KISHli2no2stNIm8A0t:-499146009) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L63)):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> in ES6 you can simply use `getUploads().map((x) => x.name)`
> </details>
> Done.

---

_[static/upload.js, line 70 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMHNoyh5fiUgqFMINs:-KISHmdAO6vtKsNeMQRt:-499146009) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L70)):_
<details><summary>

<i>Previously, intsco (Vitaly Kovalev) wrote…</i></summary>



> 1) totaly agree
> 2) extension checking is provided by fine uploader
> </details>
> Done.

---

_[static/upload.js, line 80 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIMIc6xeTXa-RdrFl28:-KISHnNoCizsK5g6D7mH:-499146009) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/static/upload.js#L80)):_
<details><summary>

<i>Previously, intsco (Vitaly Kovalev) wrote…</i></summary>



> Suprisingly onValidateBatch is called every time a new file is choosen. Not very usefull when one wants to validate several files at once.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by lomereiter** [comment]
Review status: 4 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[static/upload.js, line 14 [r2]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KISOKximuajcQtkkexK:-KISOKximuajcQtkkexL:-2046714114) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/d095de1aa9e977f549e3a332a474cbd65484344a/static/upload.js#L14)):_

> ``` JavaScript
> 
>     uploadValidate(s3Uploader) {
>         return function () {
> ```

why is it returning a function?

---

_[static/upload.js, line 36 [r2]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KISOZWLEcP-E5Dj_orU:-KISOZWLEcP-E5Dj_orV:-1598757647) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/d095de1aa9e977f549e3a332a474cbd65484344a/static/upload.js#L36)):_

> ``` JavaScript
>     }
> 
>     componentDidMound() {
> ```

typo in 'Mount'

---

_[static/upload.js, line 87 [r2]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KISNpC07rcBjK09kwb7:-KISNpC1ZEF4bZ8XWG3y:1499770286) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/d095de1aa9e977f549e3a332a474cbd65484344a/static/upload.js#L87)):_

> ``` JavaScript
>         });
> 
>         $('#trigger-upload').click(function() {
> ```

no need to use jQuery here, there's an event: http://docs.fineuploader.com/api/events.html#submit

---

_[static/upload.js, line 88 [r2]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KISO1LVEBcBwdbBauaK:-KISO1LVEBcBwdbBauaL:-1559772707) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/d095de1aa9e977f549e3a332a474cbd65484344a/static/upload.js#L88)):_

> ``` JavaScript
> 
>         $('#trigger-upload').click(function() {
>             if (thsi.uploadValidate(s3Uploader))
> ```

typo in 'this'http://docs.fineuploader.com/api/events.html#submit

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by intsco** [comment]
Review status: 4 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[static/upload.js, line 14 [r2]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KISOKximuajcQtkkexK:-KISU80HRhIWpqasmQxU:841525122) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/d095de1aa9e977f549e3a332a474cbd65484344a/static/upload.js#L14)):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> why is it returning a function?
> </details>
> Remains of the old code. Fixed

---

_[static/upload.js, line 87 [r2]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KISNpC07rcBjK09kwb7:-KISUgZdzxYJ-woF6yCx:-2033333394) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/d095de1aa9e977f549e3a332a474cbd65484344a/static/upload.js#L87)):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> no need to use jQuery here, there's an event: http://docs.fineuploader.com/api/events.html#submit
> </details>
> Submit is also fired when you select something. Can be one file only.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by DarthPumpkin** [comment]
Review status: 4 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

_[app.py, line 18 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KISj9c1WdDcO9iPkE3P:-KISj9c1WdDcO9iPkE3Q:-1102321153) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/app.py#L18)):_

> ``` Python
>     def get(self):
>         # if not self.get_cookie('session_id'):
>         # self.set_cookie('session_id', new_session_id())
> ```
1. if `new_session_id` is not to be used anymore then the occurrence in line 77 should be replaced as well and the function can be deleted
2. commented lines can be removed (also lines 114-116 and 124)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by intsco** [comment]
Review status: 4 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

_[app.py, line 18 [r1]](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KISj9c1WdDcO9iPkE3P:-KIXxipFxifQ05vcSRat:-1928274554) ([raw file](https://github.com/alexandrovteam/maori-upload/blob/9368b3edad51099d06d91f8affafdb79d1a8ca5f/app.py#L18)):_
<details><summary>

<i>Previously, DarthPumpkin (Dominik Fay) wrote…</i></summary>



> 1. if `new_session_id` is not to be used anymore then the occurrence in line 77 should be replaced as well and the function can be deleted
> 2. commented lines can be removed (also lines 114-116 and 124)
>    </details>
>    To make sure we upload every time to a new folder we need to have a new session every time we reload a page.
>    So yes, I'm for removing it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by intsco** [comment]
Review status: 4 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

_[a discussion](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIF7KwsjAh9gB0oZxPe:-KIXyDTjKdOPRCb-4mSj:-961036569) (no related file):_
<details><summary>

<i>Previously, intsco (Vitaly Kovalev) wrote…</i></summary>



> @lomereiter Your help is needed for integrating upload.js into index.jsx. At the moment it just doesn't work.
> @DarthPumpkin app.py review
> </details>
> Is it time to merge this pull request?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by DarthPumpkin** [comment]
Reviewed 1 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by lomereiter** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by lomereiter** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by lomereiter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[a discussion](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIF7KwsjAh9gB0oZxPe:-KIYCTAiiHCyQOXXgqXc:5173665) (no related file):_
<details><summary>

<i>Previously, intsco (Vitaly Kovalev) wrote…</i></summary>



> Is it time to merge this pull request?
> </details>
> OK

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by DarthPumpkin** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIF7KwsjAh9gB0oZxPe:-KIYch3hMwf4w8OJt4GZ:692331233) (no related file):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> OK
> </details>
> I  have merged master into this branch such that the pull request can be merged automatically. However you have to review the merged changes now.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by lomereiter** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIF7KwsjAh9gB0oZxPe:-KIYefpvxZML-5ibftay:2060792761) (no related file):_
<details><summary>

<i>Previously, DarthPumpkin (Dominik Fay) wrote…</i></summary>



> I  have merged master into this branch such that the pull request can be merged automatically. However you have to review the merged changes now.
> </details>
> The usual approach is rebasing feature branches onto master: http://kensheedlo.com/essays/why-you-should-use-a-rebase-workflow/, but OK

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Comment by lomereiter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2#-KIF7KwsjAh9gB0oZxPe:-KIYfLqcZo3aG8DnAhkS:676834233) (no related file):_
<details><summary>

<i>Previously, lomereiter (Artem Tarasov) wrote…</i></summary>



> The usual approach is rebasing feature branches onto master: http://kensheedlo.com/essays/why-you-should-use-a-rebase-workflow/, but OK
> </details>
> LGTM

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/alexandrovteam/maori-upload/2)_

**Pull request merged**
